name: Rust

on:
  schedule:
    - cron: '*/10 * * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run script
      run: cargo run 'https://item.rakuten.co.jp/cocoterior/c-air-kc55/'
